#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Mar 26 11:31:20 UTC 2022
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto f0235b073e3b4ad089f399e7e71fbbe5 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L axi_lite_ipif_v3_0_4 -L lib_pkg_v1_0_2 -L lib_srl_fifo_v1_0_2 -L lib_cdc_v1_0_2 -L axi_uartlite_v2_0_28 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot teststandaloneuart_behav xil_defaultlib.teststandaloneuart xil_defaultlib.glbl -log elaborate.log"
xelab -wto f0235b073e3b4ad089f399e7e71fbbe5 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L axi_lite_ipif_v3_0_4 -L lib_pkg_v1_0_2 -L lib_srl_fifo_v1_0_2 -L lib_cdc_v1_0_2 -L axi_uartlite_v2_0_28 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot teststandaloneuart_behav xil_defaultlib.teststandaloneuart xil_defaultlib.glbl -log elaborate.log

