# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/xlx_design_subsystem/xlx_design_subsystem.bd
# Block Designs: The module: 'xlx_design_subsystem' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/xlx_design_subsystem/ip/xlx_design_subsystem_axi_dwidth_converter_0_0/xlx_design_subsystem_axi_dwidth_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xlx_design_subsystem_axi_dwidth_converter_0_0 || ORIG_REF_NAME==xlx_design_subsystem_axi_dwidth_converter_0_0} -quiet] -quiet

# IP: bd/xlx_design_subsystem/ip/xlx_design_subsystem_axi_protocol_convert_0_0/xlx_design_subsystem_axi_protocol_convert_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xlx_design_subsystem_axi_protocol_convert_0_0 || ORIG_REF_NAME==xlx_design_subsystem_axi_protocol_convert_0_0} -quiet] -quiet

# IP: bd/xlx_design_subsystem/ip/xlx_design_subsystem_axi_crossbar_0_0/xlx_design_subsystem_axi_crossbar_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xlx_design_subsystem_axi_crossbar_0_0 || ORIG_REF_NAME==xlx_design_subsystem_axi_crossbar_0_0} -quiet] -quiet

# IP: bd/xlx_design_subsystem/ip/xlx_design_subsystem_axi_bram_ctrl_0_0/xlx_design_subsystem_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xlx_design_subsystem_axi_bram_ctrl_0_0 || ORIG_REF_NAME==xlx_design_subsystem_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/xlx_design_subsystem/ip/xlx_design_subsystem_blk_mem_gen_0_0/xlx_design_subsystem_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xlx_design_subsystem_blk_mem_gen_0_0 || ORIG_REF_NAME==xlx_design_subsystem_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/xlx_design_subsystem/ip/xlx_design_subsystem_axi_uartlite_0_0/xlx_design_subsystem_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xlx_design_subsystem_axi_uartlite_0_0 || ORIG_REF_NAME==xlx_design_subsystem_axi_uartlite_0_0} -quiet] -quiet

# XDC: /home/muheet/stableEnv/nova_project/nova_project.gen/sources_1/bd/xlx_design_subsystem/ip/xlx_design_subsystem_axi_dwidth_converter_0_0/xlx_design_subsystem_axi_dwidth_converter_0_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xlx_design_subsystem_axi_dwidth_converter_0_0 || ORIG_REF_NAME==xlx_design_subsystem_axi_dwidth_converter_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/muheet/stableEnv/nova_project/nova_project.gen/sources_1/bd/xlx_design_subsystem/ip/xlx_design_subsystem_axi_dwidth_converter_0_0/xlx_design_subsystem_axi_dwidth_converter_0_0_ooc.xdc

# XDC: /home/muheet/stableEnv/nova_project/nova_project.gen/sources_1/bd/xlx_design_subsystem/ip/xlx_design_subsystem_axi_protocol_convert_0_0/xlx_design_subsystem_axi_protocol_convert_0_0_ooc.xdc

# XDC: /home/muheet/stableEnv/nova_project/nova_project.gen/sources_1/bd/xlx_design_subsystem/ip/xlx_design_subsystem_blk_mem_gen_0_0/xlx_design_subsystem_blk_mem_gen_0_0_ooc.xdc

# XDC: /home/muheet/stableEnv/nova_project/nova_project.gen/sources_1/bd/xlx_design_subsystem/ip/xlx_design_subsystem_axi_uartlite_0_0/xlx_design_subsystem_axi_uartlite_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xlx_design_subsystem_axi_uartlite_0_0 || ORIG_REF_NAME==xlx_design_subsystem_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/muheet/stableEnv/nova_project/nova_project.gen/sources_1/bd/xlx_design_subsystem/ip/xlx_design_subsystem_axi_uartlite_0_0/xlx_design_subsystem_axi_uartlite_0_0_ooc.xdc

# XDC: /home/muheet/stableEnv/nova_project/nova_project.gen/sources_1/bd/xlx_design_subsystem/ip/xlx_design_subsystem_axi_uartlite_0_0/xlx_design_subsystem_axi_uartlite_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xlx_design_subsystem_axi_uartlite_0_0 || ORIG_REF_NAME==xlx_design_subsystem_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/muheet/stableEnv/nova_project/nova_project.gen/sources_1/bd/xlx_design_subsystem/xlx_design_subsystem_ooc.xdc
