# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/nova_project/nova_project.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nova_project || ORIG_REF_NAME==nova_project} -quiet] -quiet

# IP: bd/nova_project/ip/nova_project_axi_dwidth_converter_0_0/nova_project_axi_dwidth_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nova_project_axi_dwidth_converter_0_0 || ORIG_REF_NAME==nova_project_axi_dwidth_converter_0_0} -quiet] -quiet

# IP: bd/nova_project/ip/nova_project_axi_protocol_convert_0_0/nova_project_axi_protocol_convert_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nova_project_axi_protocol_convert_0_0 || ORIG_REF_NAME==nova_project_axi_protocol_convert_0_0} -quiet] -quiet

# IP: bd/nova_project/ip/nova_project_axi_crossbar_0_0/nova_project_axi_crossbar_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nova_project_axi_crossbar_0_0 || ORIG_REF_NAME==nova_project_axi_crossbar_0_0} -quiet] -quiet

# IP: bd/nova_project/ip/nova_project_axi_bram_ctrl_0_0/nova_project_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nova_project_axi_bram_ctrl_0_0 || ORIG_REF_NAME==nova_project_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/nova_project/ip/nova_project_blk_mem_gen_0_0/nova_project_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nova_project_blk_mem_gen_0_0 || ORIG_REF_NAME==nova_project_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/nova_project/ip/nova_project_axi_protocol_convert_1_0/nova_project_axi_protocol_convert_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nova_project_axi_protocol_convert_1_0 || ORIG_REF_NAME==nova_project_axi_protocol_convert_1_0} -quiet] -quiet

# IP: bd/nova_project/ip/nova_project_axi_dwidth_converter_1_0/nova_project_axi_dwidth_converter_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nova_project_axi_dwidth_converter_1_0 || ORIG_REF_NAME==nova_project_axi_dwidth_converter_1_0} -quiet] -quiet

# IP: bd/nova_project/ip/nova_project_axi_crossbar_1_0/nova_project_axi_crossbar_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nova_project_axi_crossbar_1_0 || ORIG_REF_NAME==nova_project_axi_crossbar_1_0} -quiet] -quiet

# IP: bd/nova_project/ip/nova_project_axi_uartlite_0_1/nova_project_axi_uartlite_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nova_project_axi_uartlite_0_1 || ORIG_REF_NAME==nova_project_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/nova_project/ip/nova_project_axi_uartlite_0_2/nova_project_axi_uartlite_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nova_project_axi_uartlite_0_2 || ORIG_REF_NAME==nova_project_axi_uartlite_0_2} -quiet] -quiet

# XDC: /home/muheet/uart_afi/nova_project/nova_project.gen/sources_1/bd/nova_project/ip/nova_project_axi_dwidth_converter_0_0/nova_project_axi_dwidth_converter_0_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==nova_project_axi_dwidth_converter_0_0 || ORIG_REF_NAME==nova_project_axi_dwidth_converter_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/muheet/uart_afi/nova_project/nova_project.gen/sources_1/bd/nova_project/ip/nova_project_axi_dwidth_converter_0_0/nova_project_axi_dwidth_converter_0_0_ooc.xdc

# XDC: /home/muheet/uart_afi/nova_project/nova_project.gen/sources_1/bd/nova_project/ip/nova_project_axi_protocol_convert_0_0/nova_project_axi_protocol_convert_0_0_ooc.xdc

# XDC: /home/muheet/uart_afi/nova_project/nova_project.gen/sources_1/bd/nova_project/ip/nova_project_blk_mem_gen_0_0/nova_project_blk_mem_gen_0_0_ooc.xdc

# XDC: /home/muheet/uart_afi/nova_project/nova_project.gen/sources_1/bd/nova_project/ip/nova_project_axi_protocol_convert_1_0/nova_project_axi_protocol_convert_1_0_ooc.xdc

# XDC: /home/muheet/uart_afi/nova_project/nova_project.gen/sources_1/bd/nova_project/ip/nova_project_axi_dwidth_converter_1_0/nova_project_axi_dwidth_converter_1_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==nova_project_axi_dwidth_converter_1_0 || ORIG_REF_NAME==nova_project_axi_dwidth_converter_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/muheet/uart_afi/nova_project/nova_project.gen/sources_1/bd/nova_project/ip/nova_project_axi_dwidth_converter_1_0/nova_project_axi_dwidth_converter_1_0_ooc.xdc

# XDC: /home/muheet/uart_afi/nova_project/nova_project.gen/sources_1/bd/nova_project/ip/nova_project_axi_uartlite_0_1/nova_project_axi_uartlite_0_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==nova_project_axi_uartlite_0_1 || ORIG_REF_NAME==nova_project_axi_uartlite_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/muheet/uart_afi/nova_project/nova_project.gen/sources_1/bd/nova_project/ip/nova_project_axi_uartlite_0_1/nova_project_axi_uartlite_0_1_ooc.xdc

# XDC: /home/muheet/uart_afi/nova_project/nova_project.gen/sources_1/bd/nova_project/ip/nova_project_axi_uartlite_0_1/nova_project_axi_uartlite_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==nova_project_axi_uartlite_0_1 || ORIG_REF_NAME==nova_project_axi_uartlite_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/muheet/uart_afi/nova_project/nova_project.gen/sources_1/bd/nova_project/ip/nova_project_axi_uartlite_0_2/nova_project_axi_uartlite_0_2_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==nova_project_axi_uartlite_0_2 || ORIG_REF_NAME==nova_project_axi_uartlite_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/muheet/uart_afi/nova_project/nova_project.gen/sources_1/bd/nova_project/ip/nova_project_axi_uartlite_0_2/nova_project_axi_uartlite_0_2_ooc.xdc

# XDC: /home/muheet/uart_afi/nova_project/nova_project.gen/sources_1/bd/nova_project/ip/nova_project_axi_uartlite_0_2/nova_project_axi_uartlite_0_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==nova_project_axi_uartlite_0_2 || ORIG_REF_NAME==nova_project_axi_uartlite_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/muheet/uart_afi/nova_project/nova_project.gen/sources_1/bd/nova_project/nova_project_ooc.xdc
